apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tamagrotchi.secretName" . }}
  labels:
    {{- include "tamagrotchi.labels" . | nindent 4 }}
type: Opaque
stringData:
  otlp-base: {{ .Values.otlp.base | quote }}
  otlp-auth: {{ .Values.otlp.auth | quote }}
