#!/usr/bin/env python3
"""
png_to_lvgl.py — Convert sprite sheet PNGs to LVGL v9 C++ source files.

Usage:
    python3 tools/png_to_lvgl.py src/sprites/<file>.png [frame_width]

  frame_width  Width of a single frame in pixels (default = image height).

Output:
    One .cpp file per frame, written alongside the PNG in src/sprites/.
    Each file defines an `lv_image_dsc_t` using LV_COLOR_FORMAT_RGB565A8.

Integration:
    1. Run this script for each PNG.
    2. Add extern declarations to src/sprites/grot_frames.h.
    3. Wire the new descriptors into the frame tables in grot_frames.cpp.
    4. Remove the corresponding placeholder entries.
"""

import sys
import os
from PIL import Image

HEADER = """\
// AUTO-GENERATED by tools/png_to_lvgl.py — do not edit manually.
#include <lvgl.h>

"""

def to_rgb565(r, g, b):
    """Pack R,G,B (0-255) into a 16-bit RGB565 value."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def convert_frame(img_rgba, var_name):
    """
    Convert an RGBA PIL image to LVGL v9 RGB565A8 C++ source.

    Data layout (RGB565A8):
      - All RGB565 pixels, row by row, each pixel 2 bytes little-endian.
      - All alpha bytes, row by row, 1 byte per pixel.
    stride = width * 2  (bytes per row of the RGB565 block)
    """
    w, h = img_rgba.size
    pixels = list(img_rgba.getdata())

    rgb_bytes = []
    alpha_bytes = []
    for r, g, b, a in pixels:
        v = to_rgb565(r, g, b)
        rgb_bytes.append(v & 0xFF)        # low byte
        rgb_bytes.append((v >> 8) & 0xFF) # high byte
        alpha_bytes.append(a)

    all_bytes = rgb_bytes + alpha_bytes

    # Format as C hex array, 16 bytes per line
    lines = []
    for i in range(0, len(all_bytes), 16):
        chunk = all_bytes[i:i+16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    hex_block = "\n".join(lines)

    stride = w * 2
    data_size = len(all_bytes)

    return f"""{HEADER}static const LV_ATTRIBUTE_MEM_ALIGN uint8_t _{var_name}_map[] = {{
{hex_block}
}};

// extern gives external linkage so other TUs can reference this const
extern const lv_image_dsc_t {var_name} = {{
    .header = {{
        .magic  = LV_IMAGE_HEADER_MAGIC,
        .cf     = LV_COLOR_FORMAT_RGB565A8,
        .flags  = 0,
        .w      = {w},
        .h      = {h},
        .stride = {stride},
    }},
    .data_size = {data_size},
    .data      = _{var_name}_map,
}};
"""

def slugify(name):
    """Convert a filename stem to a valid C identifier."""
    return name.replace("-", "_").replace(" ", "_")

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    png_path = sys.argv[1]
    if not os.path.isfile(png_path):
        print(f"Error: file not found: {png_path}")
        sys.exit(1)

    sheet = Image.open(png_path).convert("RGBA")
    sheet_w, sheet_h = sheet.size

    frame_w = int(sys.argv[2]) if len(sys.argv) >= 3 else sheet_h
    if sheet_w % frame_w != 0:
        print(f"Warning: sheet width {sheet_w} is not divisible by frame width {frame_w}")

    n_frames = sheet_w // frame_w
    stem = slugify(os.path.splitext(os.path.basename(png_path))[0])
    out_dir = os.path.dirname(png_path)

    print(f"{png_path}: {sheet_w}x{sheet_h}, {n_frames} frame(s) at {frame_w}x{sheet_h}")

    for i in range(n_frames):
        frame = sheet.crop((i * frame_w, 0, (i + 1) * frame_w, sheet_h))
        var_name = f"{stem}_{i}"
        cpp = convert_frame(frame, var_name)
        out_path = os.path.join(out_dir, f"{var_name}.cpp")
        with open(out_path, "w") as f:
            f.write(cpp)
        print(f"  -> {out_path}  ({frame_w}x{sheet_h}, var: {var_name})")

    print()
    print("Next steps:")
    print(f"  1. Add to grot_frames.h:  extern const lv_image_dsc_t {stem}_0; // etc.")
    print(f"  2. Wire into frame tables in grot_frames.cpp.")
    print(f"  3. Remove the matching placeholder make_dsc() calls.")

if __name__ == "__main__":
    main()
