#pragma once
#include <stdint.h>

// =============================================================================
// Button events — generated by buttons_update() and consumed by buttons_get_event()
// =============================================================================
enum class ButtonEvent : uint8_t {
    NONE    = 0,
    A_PRESS = 1,   // Button A short press (Feed)
    B_PRESS = 2,   // Button B short press (Menu)
    C_PRESS = 3,   // Button C short press (Play)
    A_LONG  = 4,   // Button A long press (>800 ms)
    B_LONG  = 5,   // Button B long press (Medicine)
    C_LONG  = 6,   // Button C long press
};

// Call once in setup()
void buttons_init();

// Call every loop() — reads GPIOs, debounces, enqueues events
void buttons_update();

// Returns the oldest queued event (NONE if queue empty). Non-blocking.
ButtonEvent buttons_get_event();
